import type { TimelineEvent } from "@/lib/types";

export const timeline: TimelineEvent[] = [
  {
    year: "1983",
    title: "Chaum publishes blind signatures",
    body: "Berkeley cryptographer David Chaum publishes the blind-signature scheme behind untraceable electronic cash — a bank that can sign digital coins without seeing them. The dream of private digital money is born a decade before the web.",
    glow: "amber",
    era: "cypherpunk",
  },
  {
    year: "1993",
    date: "March 1993",
    title: "A Cypherpunk's Manifesto",
    body: "Eric Hughes distils the young mailing list's ethos: \"Privacy is necessary for an open society in the electronic age.\" The method is stated in three words that still define the movement — cypherpunks write code.",
    glow: "amber",
    era: "cypherpunk",
  },
  {
    year: "1997",
    title: "Hashcash: proof-of-work is invented",
    body: "Adam Back proposes Hashcash, an anti-spam scheme forcing email senders to burn a little computation per message. The insight that provable, wasted work can act as an unforgeable cost will become the engine of Bitcoin mining.",
    glow: "green",
    era: "cypherpunk",
  },
  {
    year: "1998",
    title: "b-money and bit gold",
    body: "Wei Dai's b-money and Nick Szabo's bit gold independently sketch money maintained by pseudonymous strangers, created through computation, ruled by no bank. Neither ships — the puzzle of decentralised consensus is still missing its keystone.",
    glow: "violet",
    era: "cypherpunk",
  },
  {
    year: "2008",
    date: "31 October 2008",
    title: "The Bitcoin whitepaper",
    body: "Weeks after Lehman Brothers falls, the pseudonymous Satoshi Nakamoto posts nine pages describing peer-to-peer electronic cash — citing Hashcash and b-money, and solving the consensus puzzle by using proof-of-work to order history itself.",
    glow: "cyan",
    era: "cypherpunk",
  },
  {
    year: "2009",
    date: "3 January 2009",
    title: "The genesis block",
    body: "Satoshi mines Bitcoin's first block, embedding a newspaper headline about bank bailouts — timestamp and thesis statement in one. The first transaction goes to veteran cypherpunk Hal Finney. Twenty years of failed digital cash finally ships.",
    glow: "amber",
    era: "cypherpunk",
  },
  {
    year: "2013",
    date: "November 2013",
    title: "The Ethereum whitepaper",
    body: "Nineteen-year-old Vitalik Buterin proposes a blockchain with a built-in programming language: if code can run money, it can run any institution expressible as rules. Bitcoin's single application becomes a general-purpose world computer.",
    glow: "cyan",
    era: "genesis",
  },
  {
    year: "2014",
    date: "July 2014",
    title: "The ether crowdsale",
    body: "Ethereum funds itself by selling ETH for bitcoin over 42 days, raising roughly $18 million — one of the first great crowdfunded protocols. Thousands of strangers buy fuel for a computer that doesn't exist yet.",
    glow: "magenta",
    era: "genesis",
  },
  {
    year: "2015",
    date: "30 July 2015",
    title: "Frontier: Ethereum goes live",
    body: "The Ethereum network launches in deliberately raw form — a frontier for developers, not consumers. The world computer boots, and the first smart contracts deploy to an address space that will one day hold hundreds of billions in value.",
    glow: "green",
    era: "genesis",
  },
  {
    year: "2016",
    date: "June–July 2016",
    title: "The DAO hack and the fork",
    body: "A crowd-funded venture DAO holding a huge share of all ETH is drained through a reentrancy flaw. The community splits over rescuing the funds: the resulting hard fork creates today's Ethereum, while dissenters keep the original chain as Ethereum Classic. 'Code is law' meets its first constitutional crisis.",
    glow: "magenta",
    era: "genesis",
  },
  {
    year: "2017",
    title: "ICO boom and CryptoKitties",
    body: "Token sales raise billions on Ethereum in a euphoric, often reckless funding wave, while a game about breeding cartoon cats congests the entire network. The lesson lands twice over: demand for the world computer is real, and it desperately needs to scale.",
    glow: "violet",
    era: "expansion",
  },
  {
    year: "2020",
    date: "Summer 2020",
    title: "DeFi summer",
    body: "Lending markets, automated exchanges, and yield farming ignite: billions in value pour into open financial protocols that snap together like software libraries. 'Money legos' stop being a metaphor and start being a market.",
    glow: "green",
    era: "expansion",
  },
  {
    year: "2020",
    date: "1 December 2020",
    title: "The Beacon Chain launches",
    body: "Ethereum's proof-of-stake heart starts beating in parallel with the main network, secured by validators staking 32 ETH each. For two years it runs flawlessly — a dress rehearsal for the most delicate upgrade in crypto history.",
    glow: "cyan",
    era: "expansion",
  },
  {
    year: "2021",
    title: "NFT mania and EIP-1559",
    body: "A Beeple collage sells at Christie's for $69 million and NFT trading goes vertical in a full-blown cultural mania. Beneath the noise, the London upgrade ships EIP-1559 — burning a portion of every fee and rewiring ETH's monetary mechanics for good.",
    glow: "magenta",
    era: "expansion",
  },
  {
    year: "2022",
    date: "15 September 2022",
    title: "The Merge",
    body: "Ethereum swaps proof-of-work for proof-of-stake in mid-flight — no downtime, no lost funds — cutting its energy use by roughly 99.95%. Often compared to changing an aircraft's engines mid-air, it lands without a scratch.",
    glow: "cyan",
    era: "merge",
  },
  {
    year: "2023",
    date: "12 April 2023",
    title: "Shapella unlocks withdrawals",
    body: "The Shanghai/Capella upgrade lets validators withdraw staked ETH for the first time, closing the loop on proof-of-stake. Feared as an exit stampede, it proves the opposite: with the lock-up risk gone, staking participation climbs steadily.",
    glow: "green",
    era: "merge",
  },
  {
    year: "2024",
    date: "13 March 2024",
    title: "Dencun: blobs collapse L2 fees",
    body: "EIP-4844 gives rollups cheap, temporary 'blob' data space instead of permanent block space. Layer 2 fees fall by orders of magnitude overnight — from dollars to cents — and the rollup-centric roadmap stops being a promise and starts being a bill.",
    glow: "violet",
    era: "merge",
  },
  {
    year: "2024",
    date: "23 July 2024",
    title: "Spot ETH ETFs begin trading",
    body: "US regulators approve spot ether exchange-traded funds, putting ETH a brokerage click away from pensions and portfolios. The asset born on a cypherpunk mailing list is now listed alongside index funds.",
    glow: "amber",
    era: "merge",
  },
  {
    year: "2025",
    date: "7 May 2025",
    title: "Pectra ships",
    body: "The Prague/Electra upgrade lands account-abstraction powers for ordinary wallets via EIP-7702, raises validator limits, and doubles blob capacity. Wallets start behaving like smart accounts — gas sponsorship, batching, recovery — without users migrating anywhere.",
    glow: "cyan",
    era: "horizon",
  },
  {
    year: "2026+",
    title: "The endgame: rollups, blobs, and ZK",
    body: "The roadmap converges on a settled shape: layer 1 as a maximally neutral court of settlement and data availability, scaled by data-availability sampling; execution living on rollups; and zero-knowledge proofs verifying ever more of the stack. If it works, using Ethereum will feel like using the internet — nobody asks which layer they're on.",
    glow: "violet",
    era: "horizon",
  },
];
